# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SheHacks2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SheHacks2018

  target 'SheHacks2018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SheHacks2018UITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end
